databases:
  - name: ai-platform-db
    plan: free
    region: oregon

services:
  # Flask Backend with integrated Frontend
  - type: web
    name: ai-platform-fullstack
    runtime: python3
    buildCommand: |
      # Install Node.js and build frontend
      curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
      sudo apt-get install -y nodejs
      cd frontend && npm ci && DISABLE_ESLINT_PLUGIN=true CI=false npm run build
      cd ../backend && pip install -r requirements.txt
      # Run database migrations with enhanced logging
      export FLASK_APP=app.py
      export PYTHONPATH=$(pwd):$PYTHONPATH
      echo "=== Starting database migration ==="
      echo "Current directory: $(pwd)"
      echo "Flask app: $FLASK_APP"
      echo "PYTHONPATH: $PYTHONPATH"
      echo "Database URL: $DATABASE_URL"
      echo "Python version: $(python --version)"
      echo "Flask version: $(python -c 'import flask; print(flask.__version__)')"
      echo "Checking database connectivity..."
      python -c "from app import create_app; app = create_app(); print('Database connection successful')" || echo "Database connection failed"
      echo "Running migrations using Flask CLI with optimized environment..."
      export SKIP_AGENT_INIT=1
      flask db upgrade || (echo "Flask CLI migration failed with exit code $?"; echo "Trying simplified Python script..."; python simple_migrate.py) || (echo "All migration attempts failed with exit code $?"; exit 1)
      echo "=== Migration completed successfully ==="
    startCommand: cd backend && gunicorn wsgi:application
    plan: free # Change to 'starter' or higher for production
    region: oregon
    rootDir: .
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true # Render will generate a secure key
      - key: JWT_SECRET_KEY
        generateValue: true # Render will generate a secure key
      - key: DATABASE_URL
        fromDatabase:
          name: ai-platform-db
          property: connectionString
      # These need to be set manually in Render dashboard
      - key: OPENAI_API_KEY
        sync: false # Must be set in dashboard
      - key: OPENAI_BASE_URL
        value: https://api.openai.com/v1
      - key: OPENAI_DEFAULT_MODEL
        value: gpt-4o
      - key: REACT_APP_API_URL
        value: /api

# Note: This render.yaml provides a template but manual setup through
# the Render dashboard is recommended for better control over sensitive
# environment variables like OPENAI_API_KEY