"""Add offers table for offer assistant functionality

Revision ID: 47921cfd1b6c
Revises: 9d02a0d64f19
Create Date: 2025-08-31 16:43:37.461338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47921cfd1b6c'
down_revision = '9d02a0d64f19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    from alembic import context
    from sqlalchemy import inspect

    # Get the database inspector
    conn = context.get_bind()
    inspector = inspect(conn)
    existing_tables = inspector.get_table_names()

    # Only create competitions table if it doesn't exist (should have been created in previous migration)
    if 'competitions' not in existing_tables:
        op.create_table('competitions',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('business_profile_id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('url', sa.String(length=500), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('usp', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['business_profile_id'], ['business_profiles.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    # Only create offers table if it doesn't exist
    if 'offers' not in existing_tables:
        op.create_table('offers',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('business_profile_id', sa.String(length=36), nullable=False),
        sa.Column('type', sa.String(length=20), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('unit', sa.String(length=50), nullable=False),
        sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['business_profile_id'], ['business_profiles.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offers')
    op.drop_table('competitions')
    # ### end Alembic commands ###
