"""Add analysis_request table for background processing

Revision ID: 49e76ac1e851
Revises: e2554aa15b05
Create Date: 2025-08-28 00:06:08.845431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49e76ac1e851'
down_revision = 'e2554aa15b05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('openai_response_id', sa.String(length=255), nullable=False),
    sa.Column('website_url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('analysis_result', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_requests_openai_response_id'), ['openai_response_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_requests_openai_response_id'))

    op.drop_table('analysis_requests')
    # ### end Alembic commands ###
