"""Remove author_name field from user_styles table

Revision ID: 8b916055957d
Revises: ff764e82b325
Create Date: 2025-09-04 21:15:02.328236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b916055957d'
down_revision = 'ff764e82b325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_styles', schema=None) as batch_op:
        batch_op.drop_column('author_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_styles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_name', sa.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
