"""Add business_profile_id to user_styles table

Revision ID: 90de443dda9f
Revises: c1d2e3f4g5h6
Create Date: 2025-09-07 11:21:54.300551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90de443dda9f'
down_revision = 'c1d2e3f4g5h6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_styles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_profile_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_user_styles_business_profile_id', 'business_profiles', ['business_profile_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_styles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_styles_business_profile_id', type_='foreignkey')
        batch_op.drop_column('business_profile_id')

    # ### end Alembic commands ###
