"""Drop tool_costs table - use tool class constants instead

Revision ID: 970cf347db75
Revises: fa92d95a94d2
Create Date: 2025-09-10 20:35:39.158687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '970cf347db75'
down_revision = 'fa92d95a94d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tool_costs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_costs',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('tool_slug', sa.VARCHAR(length=100), nullable=False),
    sa.Column('agent_slug', sa.VARCHAR(length=100), nullable=False),
    sa.Column('tool_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('cost', sa.INTEGER(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tool_slug')
    )
    # ### end Alembic commands ###
