"""Add campaigns table for campaign generator feature

Revision ID: be9ad9dd0816
Revises: 47921cfd1b6c
Create Date: 2025-09-02 15:47:41.754120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be9ad9dd0816'
down_revision = '47921cfd1b6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('business_profile_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('goal', sa.String(length=100), nullable=False),
    sa.Column('budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('selected_products', sa.JSON(), nullable=True),
    sa.Column('strategy_summary', sa.Text(), nullable=True),
    sa.Column('timeline', sa.Text(), nullable=True),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('sales_funnel_steps', sa.Text(), nullable=True),
    sa.Column('channels', sa.JSON(), nullable=True),
    sa.Column('channels_rationale', sa.JSON(), nullable=True),
    sa.Column('recommended_budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('risks_recommendations', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['business_profile_id'], ['business_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaigns')
    # ### end Alembic commands ###
