"""Add style_name and sample_texts to user_styles table

Revision ID: c1d2e3f4g5h6
Revises: 8b916055957d
Create Date: 2025-09-05 21:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d2e3f4g5h6'
down_revision = '8b916055957d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_styles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('style_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('sample_texts', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_styles', schema=None) as batch_op:
        batch_op.drop_column('sample_texts')
        batch_op.drop_column('style_name')

    # ### end Alembic commands ###